def get_default_word_bank():
    """Load a default set of commonly used AI words and phrases"""
    # Common words from various sources
    default_words = [
        # Words identified from multiple sources as common in AI text
        # ("delve", 10, "verb", "GPTZero"),
        # ("whilst", 9, "conjunction", "ZeroGPT"),
        # ("furthermore", 8, "conjunction", "ZeroGPT"),
        # ("navigate", 8, "verb", "GPTZero"),
        # ("indeed", 7, "adverb", "ZeroGPT"),
        # ("utilize", 7, "verb", "ZeroGPT"),
        # ("leverage", 7, "verb", "ZeroGPT"),
        # ("robust", 7, "adjective", "ZeroGPT"),
        # ("optimal", 7, "adjective", "ZeroGPT"),
        # ("showcase", 6, "verb", "ZeroGPT"),
        # ("essentially", 6, "adverb", "ZeroGPT"),
        # ("ultimately", 6, "adverb", "ZeroGPT"),
        # ("myriad", 6, "adjective", "ZeroGPT"),
        # ("seamless", 6, "adjective", "ZeroGPT"),
        # ("plethora", 6, "noun", "ZeroGPT"),
        # ("harness", 6, "verb", "ZeroGPT"),
        # ("elevate", 10, "verb", "GPTZero"),
        # ("tapestry", 9, "noun", "GPTZero"),
        # ("captivate", 8, "verb", "GPTZero"),
        # ("testament", 8, "noun", "GPTZero"),
        # ("nuanced", 7, "adjective", "GPTZero"),
        # ("enhance", 7, "verb", "ZeroGPT"),
        # ("facilitate", 7, "verb", "ZeroGPT"),
        # # ("comprehensive", 7, "adjective", "ZeroGPT"),
        # ("innovative", 6, "adjective", "ZeroGPT"),
        # ("streamline", 6, "verb", "ZeroGPT"),
        # ("synergy", 6, "noun", "ZeroGPT"),
        # ("paradigm", 6, "noun", "ZeroGPT"),
        # ("empower", 6, "verb", "ZeroGPT"),
        # ("revolutionize", 6, "verb", "ZeroGPT"),
        # ("transformative", 6, "adjective", "ZeroGPT"),
        # ("ecosystem", 5, "noun", "ZeroGPT"),
        # ("unprecedented", 5, "adjective", "ZeroGPT"),
        # ("cultivate", 5, "verb", "ZeroGPT"),
        # ("catalyst", 5, "noun", "ZeroGPT"),
        # ("disrupt", 5, "verb", "ZeroGPT"),
        # ("holistic", 5, "adjective", "ZeroGPT"),
        # ("cutting-edge", 5, "adjective", "ZeroGPT"),
        # ("sustainable", 5, "adjective", "ZeroGPT"),
        # ("innovative", 5, "adjective", "ZeroGPT"),
        # ("strategic", 5, "adjective", "ZeroGPT"),
        # ("foster", 5, "verb", "ZeroGPT"),
        # ("streamlined", 5, "adjective", "ZeroGPT"),
        # ("implementation", 5, "noun", "ZeroGPT"),
        # ("integration", 5, "noun", "ZeroGPT"),
        # ("methodology", 5, "noun", "ZeroGPT"),
        # ("functionality", 5, "noun", "ZeroGPT"),
        # ("optimization", 5, "noun", "ZeroGPT"),
        # ("infrastructure", 5, "noun", "ZeroGPT"),
        # ("initiative", 5, "noun", "ZeroGPT"),
    ]

    # Common phrases from various sources
    default_phrases = [
        ("a beacon of hope", 1, "general", "user"),
        ("a complex multifaceted", 1, "general", "user"),
        ("a crucial development", 1, "general", "user"),
        ("a key takeaway is", 1, "general", "user"),
        ("a multifaceted approach", 1, "general", "user"),
        ("a nuanced understanding", 1, "general", "user"),
        ("a plethora of", 1, "general", "user"),
        ("a profound implication", 1, "general", "user"),
        ("a prominent figure", 1, "general", "user"),
        ("a rich tapestry", 1, "general", "user"),
        ("a serf reminder", 1, "general", "user"),
        ("a significant implication", 1, "general", "user"),
        ("a significant milestone", 1, "general", "user"),
        ("a significant step forward", 1, "general", "user"),
        ("a significant stride", 1, "general", "user"),
        ("a significant turning point", 1, "general", "user"),
        ("a stark reminder", 1, "general", "user"),
        ("a unique blend", 1, "general", "user"),
        ("a wide range of", 1, "general", "user"),
        ("add a layer", 1, "general", "user"),
        ("add an extra layer", 1, "general", "user"),
        ("add depth to", 1, "general", "user"),
        ("additionally", 1, "general", "user"),
        ("address the root cause", 1, "general", "user"),
        ("adds a layer of complexity", 1, "general", "user"),
        ("advancing the understanding", 1, "general", "user"),
        ("aim to explore", 1, "general", "user"),
        ("align", 1, "general", "user"),
        ("all things considered", 1, "general", "user"),
        ("also", 1, "general", "user"),
        ("alternatively", 1, "general", "user"),
        ("although", 1, "general", "user"),
        ("an important consideration is", 1, "general", "user"),
        ("an indelible mark", 1, "general", "user"),
        ("an unwavering commitment", 1, "general", "user"),
        ("analogies to being a conductor or to music", 1, "general", "user"),
        ("arguably", 1, "general", "user"),
        ("as a professional", 1, "general", "user"),
        ("as a result", 1, "general", "user"),
        ("as an ai language model", 1, "general", "user"),
        ("as mentioned earlier", 1, "general", "user"),
        ("as of my last update", 1, "general", "user"),
        ("as previously mentioned", 1, "general", "user"),
        ("as we have seen", 1, "general", "user"),
        ("as well as", 1, "general", "user"),
        ("at its core", 1, "general", "user"),
        ("beacon", 1, "general", "user"),
        ("because", 1, "general", "user"),
        ("bespoke", 1, "general", "user"),
        ("bolster", 1, "general", "user"),
        ("broad implications", 1, "general", "user"),
        ("broadly speaking", 1, "general", "user"),
        ("bustling", 1, "general", "user"),
        ("captivate", 1, "general", "user"),
        ("casting long shadows", 1, "general", "user"),
        ("catalyst", 1, "general", "user"),
        ("colons", 1, "general", "user"),
        ("commitment to excellence", 1, "general", "user"),
        ("comprehensive", 1, "general", "user"),
        ("conclusion of the study demonstrates", 1, "general", "user"),
        ("conclusion of the study provides", 1, "general", "user"),
        ("confluence", 1, "general", "user"),
        ("consequently", 1, "general", "user"),
        ("context", 1, "general", "user"),
        ("continue to inspire", 1, "general", "user"),
        ("continues to inspire", 1, "general", "user"),
        ("contribute to understanding", 1, "general", "user"),
        ("contributes to understanding", 1, "general", "user"),
        ("crucial", 1, "general", "user"),
        ("crucial role in understanding", 1, "general", "user"),
        ("crucially", 1, "general", "user"),
        ("cultivate", 1, "general", "user"),
        ("curated collection", 1, "general", "user"),
        ("curiosity piques", 1, "general", "user"),
        ("cutting-edge", 1, "general", "user"),
        ("dance", 1, "general", "user"),
        ("delve", 1, "general", "user"),
        ("delve deeper into", 1, "general", "user"),
        ("delve into", 1, "general", "user"),
        ("despite", 1, "general", "user"),
        ("despite the challenge faced", 1, "general", "user"),
        ("despite the face", 1, "general", "user"),
        ("differentiate", 1, "general", "user"),
        ("disrupt", 1, "general", "user"),
        ("dive into", 1, "general", "user"),
        ("due to", 1, "general", "user"),
        ("dynamic", 1, "general", "user"),
        ("ecosystem", 1, "general", "user"),
        ("elevate", 1, "general", "user"),
        ("embark", 1, "general", "user"),
        ("embark on a journey", 1, "general", "user"),
        ("emphasise", 1, "general", "user"),
        ("emphasize the need", 1, "general", "user"),
        ("empower", 1, "general", "user"),
        ("endure a legacy", 1, "general", "user"),
        ("enhance", 1, "general", "user"),
        ("enhance the understanding", 1, "general", "user"),
        ("enhances the understanding", 1, "general", "user"),
        ("enigma", 1, "general", "user"),
        ("enrich", 1, "general", "user"),
        ("ensure", 1, "general", "user"),
        ("essential", 1, "general", "user"),
        ("essential to recognize", 1, "general", "user"),
        ("essentially", 1, "general", "user"),
        ("esteemed", 1, "general", "user"),
        ("even if", 1, "general", "user"),
        ("even though", 1, "general", "user"),
        ("evolve", 1, "general", "user"),
        ("experts agree", 1, "general", "user"),
        ("explore", 1, "general", "user"),
        ("facet", 1, "general", "user"),
        ("facilitate", 1, "general", "user"),
        ("fancy", 1, "general", "user"),
        ("finding a contribution", 1, "general", "user"),
        ("finding a shed light", 1, "general", "user"),
        ("finding an important implication", 1, "general", "user"),
        ("finding the highlight the importance", 1, "general", "user"),
        ("findings contribute to", 1, "general", "user"),
        ("firstly", 1, "general", "user"),
        ("foster", 1, "general", "user"),
        ("foster a culture of", 1, "general", "user"),
        ("fostering a sense", 1, "general", "user"),
        ("framework", 1, "general", "user"),
        ("from a broader perspective", 1, "general", "user"),
        ("functionality", 1, "general", "user"),
        ("fundamentally", 1, "general", "user"),
        ("furthermore", 1, "general", "user"),
        ("gain a comprehensive understanding", 1, "general", "user"),
        ("gain a deeper understanding", 1, "general", "user"),
        ("gain a valuable", 1, "general", "user"),
        ("gain an insight", 1, "general", "user"),
        ("gain significant attention", 1, "general", "user"),
        ("gain valuable insights", 1, "general", "user"),
        ("game changer", 1, "general", "user"),
        ("game-changing", 1, "general", "user"),
        ("garnered a significant", 1, "general", "user"),
        ("generally", 1, "general", "user"),
        ("generally speaking", 1, "general", "user"),
        ("given that", 1, "general", "user"),
        ("given the context", 1, "general", "user"),
        ("gossamer", 1, "general", "user"),
        ("harness", 1, "general", "user"),
        ("harness the power", 1, "general", "user"),
        ("help to feel a sense", 1, "general", "user"),
        ("highlight the need", 1, "general", "user"),
        ("highlight the potential", 1, "general", "user"),
        ("highlight the significance", 1, "general", "user"),
        ("highlights the importance of considering", 1, "general", "user"),
        ("hold a significant", 1, "general", "user"),
        ("holds a significant", 1, "general", "user"),
        ("holistic", 1, "general", "user"),
        ("however", 1, "general", "user"),
        ("hung heavy", 1, "general", "user"),
        ("hustle and bustle", 1, "general", "user"),
        ("i cannot browse the internet", 1, "general", "user"),
        ("i cannot provide", 1, "general", "user"),
        ("i don't have access to", 1, "general", "user"),
        ("identify the area of improvement", 1, "general", "user"),
        ("illuminate", 1, "general", "user"),
        ("implementation", 1, "general", "user"),
        ("implication to understand", 1, "general", "user"),
        ("implications of various", 1, "general", "user"),
        ("importance of the address", 1, "general", "user"),
        ("importantly", 1, "general", "user"),
        ("in conclusion", 1, "general", "user"),
        ("in contrast", 1, "general", "user"),
        ("in light of", 1, "general", "user"),
        ("in many cases", 1, "general", "user"),
        ("in order to", 1, "general", "user"),
        ("in other words", 1, "general", "user"),
        ("in summary", 1, "general", "user"),
        ("in the annals of", 1, "general", "user"),
        ("in the context of", 1, "general", "user"),
        ("in the digital age", 1, "general", "user"),
        ("in the event that", 1, "general", "user"),
        ("in the fast-paced world", 1, "general", "user"),
        ("in the realm of", 1, "general", "user"),
        ("in the world of", 1, "general", "user"),
        ("in this article", 1, "general", "user"),
        ("in today's digital era", 1, "general", "user"),
        ("in today's fast-paced world", 1, "general", "user"),
        ("indeed", 1, "general", "user"),
        ("indelible", 1, "general", "user"),
        ("influence various factors", 1, "general", "user"),
        ("infrastructure", 1, "general", "user"),
        ("initiative", 1, "general", "user"),
        ("innovative", 1, "general", "user"),
        ("insight", 1, "general", "user"),
        ("integration", 1, "general", "user"),
        ("intricacies", 1, "general", "user"),
        ("it can be argued", 1, "general", "user"),
        ("it goes without saying", 1, "general", "user"),
        ("it is essential to", 1, "general", "user"),
        ("it is important to note", 1, "general", "user"),
        ("it is widely accepted", 1, "general", "user"),
        ("it is worth mentioning", 1, "general", "user"),
        ("it is worth noting", 1, "general", "user"),
        ("it stands to reason", 1, "general", "user"),
        ("it's crucial to understand", 1, "general", "user"),
        ("it's essential to", 1, "general", "user"),
        ("it's important to note", 1, "general", "user"),
        ("it's worth mentioning that", 1, "general", "user"),
        ("it's worth noting that", 1, "general", "user"),
        ("iterative", 1, "general", "user"),
        ("journey", 1, "general", "user"),
        ("keen", 1, "general", "user"),
        ("labyrinth", 1, "general", "user"),
        ("labyrinthine", 1, "general", "user"),
        ("landscape", 1, "general", "user"),
        ("leave a lasting", 1, "general", "user"),
        ("left an indelible", 1, "general", "user"),
        ("left an indelible mark", 1, "general", "user"),
        ("let us delve", 1, "general", "user"),
        ("leverage", 1, "general", "user"),
        ("make a challenge", 1, "general", "user"),
        ("make an informed decision in regard to", 1, "general", "user"),
        ("mark a significant", 1, "general", "user"),
        ("metamorphosis", 1, "general", "user"),
        ("methodology", 1, "general", "user"),
        ("meticulous", 1, "general", "user"),
        ("meticulous attention to", 1, "general", "user"),
        ("metropolis", 1, "general", "user"),
        ("moist", 1, "general", "user"),
        ("moreover", 1, "general", "user"),
        ("moving forward", 1, "general", "user"),
        ("multifaceted", 1, "general", "user"),
        ("my friend", 1, "general", "user"),
        ("myriad", 1, "general", "user"),
        ("navigate", 1, "general", "user"),
        ("navigate the challenge", 1, "general", "user"),
        ("navigate the complex", 1, "general", "user"),
        ("navigating", 1, "general", "user"),
        ("navigating the complexities", 1, "general", "user"),
        ("need to fully understand", 1, "general", "user"),
        ("needed to fully understand", 1, "general", "user"),
        ("needless to say", 1, "general", "user"),
        ("nestled", 1, "general", "user"),
        ("nonetheless", 1, "general", "user"),
        ("notably", 1, "general", "user"),
        ("nuanced", 1, "general", "user"),
        ("offer a unique perspective", 1, "general", "user"),
        ("offer a valuable", 1, "general", "user"),
        ("offers valuable insights", 1, "general", "user"),
        ("on the other hand", 1, "general", "user"),
        ("one might consider", 1, "general", "user"),
        ("open a new avenue", 1, "general", "user"),
        ("opens new avenues", 1, "general", "user"),
        ("optimal", 1, "general", "user"),
        ("optimization", 1, "general", "user"),
        ("optimize", 1, "general", "user"),
        ("orchestrate", 1, "general", "user"),
        ("paradigm", 1, "general", "user"),
        ("paradigm shift", 1, "general", "user"),
        ("paramount", 1, "general", "user"),
        ("pave the way for the future", 1, "general", "user"),
        ("perspective", 1, "general", "user"),
        ("pesky", 1, "general", "user"),
        ("pivotal", 1, "general", "user"),
        ("pivotal role in shaping", 1, "general", "user"),
        ("play a crucial role in determining", 1, "general", "user"),
        ("play a significant role in shaping", 1, "general", "user"),
        ("played a significant role in shaping", 1, "general", "user"),
        ("plays a crucial role", 1, "general", "user"),
        ("plays a crucial role in shaping", 1, "general", "user"),
        ("plays a crucial role in understanding", 1, "general", "user"),
        ("plethora", 1, "general", "user"),
        ("pose a significant challenge", 1, "general", "user"),
        ("present a unique challenge", 1, "general", "user"),
        ("profound", 1, "general", "user"),
        ("promptly", 1, "general", "user"),
        ("provide a comprehensive overview", 1, "general", "user"),
        ("provide a framework to understand", 1, "general", "user"),
        ("provide a valuable insight", 1, "general", "user"),
        ("provide an insight", 1, "general", "user"),
        ("provide the text", 1, "general", "user"),
        ("provide valuable insights", 1, "general", "user"),
        ("provides valuable insights", 1, "general", "user"),
        ("realm", 1, "general", "user"),
        ("refine", 1, "general", "user"),
        ("reimagine", 1, "general", "user"),
        ("remember that", 1, "general", "user"),
        ("remnant", 1, "general", "user"),
        ("require a careful consideration", 1, "general", "user"),
        ("research indicates", 1, "general", "user"),
        ("research needed to explore", 1, "general", "user"),
        ("resonate", 1, "general", "user"),
        ("reverberate", 1, "general", "user"),
        ("revolutionize", 1, "general", "user"),
        ("rich tapestry", 1, "general", "user"),
        ("robust", 1, "general", "user"),
        ("scalable solution", 1, "general", "user"),
        ("seamless", 1, "general", "user"),
        ("seamless integration", 1, "general", "user"),
        ("sense of camaraderie", 1, "general", "user"),
        ("sent shockwaves through", 1, "general", "user"),
        ("shed light on", 1, "general", "user"),
        ("showcase", 1, "general", "user"),
        ("sights unseen", 1, "general", "user"),
        ("significant", 1, "general", "user"),
        ("significant attention in recent years", 1, "general", "user"),
        ("significant contributions to the field", 1, "general", "user"),
        ("significantly", 1, "general", "user"),
        ("similarly", 1, "general", "user"),
        ("sounds unheard", 1, "general", "user"),
        ("specifically", 1, "general", "user"),
        ("strategic", 1, "general", "user"),
        ("streamline", 1, "general", "user"),
        ("streamlined", 1, "general", "user"),
        ("studies have shown", 1, "general", "user"),
        ("study highlights the importance", 1, "general", "user"),
        ("study provides a valuable", 1, "general", "user"),
        ("study shed light on", 1, "general", "user"),
        ("study sheds light on", 1, "general", "user"),
        ("subsequently", 1, "general", "user"),
        ("supercharge", 1, "general", "user"),
        ("sustainable", 1, "general", "user"),
        ("symphony", 1, "general", "user"),
        ("synergy", 1, "general", "user"),
        ("take a dive into", 1, "general", "user"),
        ("tapestry", 1, "general", "user"),
        ("tends to", 1, "general", "user"),
        ("testament", 1, "general", "user"),
        ("that being said", 1, "general", "user"),
        ("the complex interplay", 1, "general", "user"),
        ("the findings suggest", 1, "general", "user"),
        ("the importance to consider", 1, "general", "user"),
        ("the intricate relationship", 1, "general", "user"),
        ("the legacy of life", 1, "general", "user"),
        ("the multifaceted nature", 1, "general", "user"),
        ("the potential to revolutionize", 1, "general", "user"),
        ("the relentless pursuit", 1, "general", "user"),
        ("the target intervention", 1, "general", "user"),
        ("the transformative power", 1, "general", "user"),
        ("there are a few considerations", 1, "general", "user"),
        ("therefore", 1, "general", "user"),
        ("this approach allows for", 1, "general", "user"),
        ("this highlights the need", 1, "general", "user"),
        ("this is not an exhaustive list", 1, "general", "user"),
        ("this underscores the importance of", 1, "general", "user"),
        ("thus", 1, "general", "user"),
        ("to better understand", 1, "general", "user"),
        ("to consider", 1, "general", "user"),
        ("to put it simply", 1, "general", "user"),
        ("to some extent", 1, "general", "user"),
        ("to sum up", 1, "general", "user"),
        ("to summarize", 1, "general", "user"),
        ("today in the digital age", 1, "general", "user"),
        ("today the fast pace of the world", 1, "general", "user"),
        ("trajectory", 1, "general", "user"),
        ("transformative", 1, "general", "user"),
        ("treasure trove", 1, "general", "user"),
        ("treasure trove of", 1, "general", "user"),
        ("typically", 1, "general", "user"),
        ("ultimately", 1, "general", "user"),
        ("underscore", 1, "general", "user"),
        ("underscore the importance", 1, "general", "user"),
        ("underscore the need", 1, "general", "user"),
        ("understand the behavior", 1, "general", "user"),
        ("understand the complexity", 1, "general", "user"),
        ("understanding the fundamental", 1, "general", "user"),
        ("undoubtedly", 1, "general", "user"),
        ("unless", 1, "general", "user"),
        ("unlock", 1, "general", "user"),
        ("unlock the potential", 1, "general", "user"),
        ("unprecedented", 1, "general", "user"),
        ("unwavering support", 1, "general", "user"),
        ("utilize", 1, "general", "user"),
        ("validate the finding", 1, "general", "user"),
        ("valuable insights", 1, "general", "user"),
        ("various fields include", 1, "general", "user"),
        ("vibrant", 1, "general", "user"),
        ("vital", 1, "general", "user"),
        ("vital role in shaping", 1, "general", "user"),
        ("voice dripping with sarcasm", 1, "general", "user"),
        ("when it comes to", 1, "general", "user"),
        ("while", 1, "general", "user"),
        ("whilst", 1, "general", "user"),
        ("whimsical", 1, "general", "user"),
        ("whispering", 1, "general", "user"),
        ("with regard to", 1, "general", "user"),
        ("you could consider", 1, "general", "user"),
        ("you may want to", 1, "general", "user"),
        # ("In conclusion", 1, "general", "user"),
    ]

    return default_words, default_phrases